# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy files
COPY app.py /app/
COPY knn_model.pkl /app/
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Run the API
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
